#!/bin/sh 

# Both of them are procedures as they don't have return values.
# As posix does not function as it keywords mall the functions can be
# called as procedures. 
say_hello(){
	echo "Hello"
	echo "How are you?"
}

say_goodbye(){
	echo "Goodbye !"
}

say_hello
say_goodbye
