#!/bin/bash


## VARIABLES:

mess="Variables are states in the memory. Just like us humans we are
just state machines."

echo "Variables: "
echo $mess

## NOTE: NO spaces between variable names and value. 

name='hmm'
pi=3.141529
sport="Foot"

echo "name: $name"
echo "pi: $pi"
echo "Sports: {$sport}ball"

figlet -m smushmode 'hmm' | lolcat --animate --truecolor

